spring:
  profiles:
    active: local
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect #Hibernate에서 MySQL문법 사용

---
spring:
  profiles: local
#  datasource:
#    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---
spring.profiles: production
spring.profiles.include: real-db

server:
  port: 8081