spring:
  profiles:
    active: production
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---
spring.profiles: production
spring.profiles.include: real-db

server:
  port: 8080