spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  thymeleaf:
    cache: false

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fifarm
  jpa:
    show-sql: true

server:
  port: 8090

---
spring.profiles: production
spring.profiles.include: real-db

server:
  port: 8080